apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
      version: v1
  template:
    metadata:
      labels:
        app: fastapi
        version: v1
    spec:
      containers:
        - name: fastapi-v1-container
          image: dhiraj918106/fastapi-canary:v1  # ✅ Docker Hub image
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
